# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc640f5f5bb289c21924bc64c31a65d2af237f06e55fe25b309c5c7ec1a05005775ef460e98aa12617f985713915093519edc975a3d33f8ed6b2754b3e1d9166

test:
  secret_key_base: 3de2e938a9e0b3f321185b2a555d03ab5785c5790066d9b8a7cbaf6bb34d9e8b2c188b37c58a1e00037d86bbfb315fab1d28ec5a90969729a18f29bf253232e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
